const MOVIE_ACTION_TYPES = {
    MOVIE_SEARCH_SUCCESS: "MOVIE_SEARCH_SUCCESS",
    RETRIEVE_MOVIE_PLOT: "RETRIEVE_MOVIE_PLOT",
    ADD_NOMINATION_SUCCESS: "ADD_NOMINATION_SUCCESS",
    REMOVE_NOMINATION_SUCCESS: "REMOVE_NOMINATION_SUCCESS",
    RESET_SUCCESS: "RESET_SUCCESS"
  };
  
  export default MOVIE_ACTION_TYPES;